### PR TITLE
NEW: Support Python3.x(as "rpi-source3")

### PR DESCRIPTION
**Pull request by borley1211**
# Abstract

Added support for Python3 series.

# Purpose

When I used this repository in a **proxy** environment, an error due to **SSL certificate revocation** occurred in my own _Python (2 system)_ environment and **I could not use it properly**.
This update is due to the fact that it worked correctly when edited to work properly with **Python3**.
The only change is the addition of the script `rpi-source3`, but I think this is a very important and meaningful update.

### CODE REVIEW

**Comment by notro** [comment]
I'm sorry but I can't take this as-is. If we're updating to python3, we should update the script not add an extra one. 
Is python3 the default on Raspberry Pi now? If so we can update, otherwise I want to wait.

**Comment by borley1211** [comment]
@notro 
According to this information(see the .info file in the link below), `python3` (v3.7) seems to be included in Buster (the latest release version of Raspbian Lite).
[http://downloads.raspberrypi.org/raspbian_lite/images/raspbian_lite-2019-06-24/](raspbian_buster)

Therefore, I think that it is required to support the **python3 system** that will continue to be supported in the future, with the shebang as `#!/usr/bin/env python3`.

**Comment by notro** [comment]
Yes I know python3 has been included for a long time, but is it the default yet, that's the question.
This was not the case in july at least:

```
$ cat /boot/issue.txt
Raspberry Pi reference 2019-07-10
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 175dfb027ffabd4b8d5080097af0e51ed9a4a56c, stage4

$ python --version
Python 2.7.16
```

Aside from that I find it hard to believe that the certificate problem is due to the python version being used.

**Comment by borley1211** [comment]
@notro
Yes, I know that when I call `python`, a `python2` interpreter runs.
But, this is not an important issue considering the current situation where the python interpreter can be specified by a shebang at the top of the script.

**Comment by notro** [comment]
My point is that I want to stick with the Raspbian default which is python2. This is a script not a library so I'm in no rush to switch to python3. Alot of people use this script so I will only accept fixes when something is broken.

**Comment by borley1211** [comment]
@notro
As for the certificate problem, I think that it is important that **the python3 system just used the standard library as it was and no problem occurred**.

On the other hand, I understand the problems that could cause an unexpected error in an environment where this script could be used.

So, in the situation where `rpi-source` doesn't work well due to some problem, it's a ** one choice of solutions ** (i.e. no modification to traditional scripts)  I strongly hope to add it to the repository.

**Comment by notro** [comment]
rpi-source development has now moved to https://github.com/RPi-Distro/rpi-source

**Pull request closed without merging**
